#!/bin/sh
#-----------------------------------------------------------------------
# sets the environment and runs sqlminus
#-----------------------------------------------------------------------

TOP=/usr/local/sqlminus    # where cx_Oracle/python is installed
# TNS_ADMIN=/etc           # handle tnsnames location if necessary

if test -d $TOP/instantclient_11_2; then
    export ORACLE_HOME=$TOP/instantclient_11_2
fi

if test -d $TOP/instantclient_12_1; then
    export ORACLE_HOME=$TOP/instantclient_12_1
fi

export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$ORACLE_HOME
export DYLD_LIBRARY_PATH=$DYLD_LIBRARY_PATH:$ORACLE_HOME

exec $TOP/bin/python $TOP/bin/sqlminus.py "$@"
